infra

diff --git a/90-cdn/Jenkinsfile b/90-cdn/Jenkinsfile
--- a/90-cdn/Jenkinsfile
+++ b/90-cdn/Jenkinsfile
@@ -2,20 +2,22 @@ pipeline {
     agent {
         label 'agent-1'
     }
-    options {
-        // Timeout counter starts BEFORE agent is allocated
+    options{
         timeout(time: 30, unit: 'MINUTES')
         disableConcurrentBuilds()
         ansiColor('xterm')
-        // retry(1)
     }
+    // environment {
+    //     DEBUG = 'true'
+    // }
+
     parameters {
         choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select Action')
     }
     stages {
         stage('Init and Plan') {
             steps {
-                withAWS(region: 'us-east-1', credentials: 'as-creds') {
+                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                     sh """
                         cd 90-cdn
                         terraform init -reconfigure
@@ -24,42 +26,111 @@ pipeline {
                 }
             }
         }
-        stage('apply or destroy') {
-            // input {
-            //     message "Should we continue? to ${params.ACTION}"
-            //     ok "Yes, we should."
-            // }
+
+        stage('Apply or Destroy') {
+            /* input {
+                message "Should we continue to ${params.ACTION}"
+                ok "Yes, we should."
+            } */
             steps {
-                withAWS(region: 'us-east-1', credentials: 'as-creds') {
+                withAWS(region: 'us-east-1', credentials: 'as creds') {
                     sh """
-                        cd 90-cdn
-                        if [ "${params.ACTION}" == "apply" ]
-                         then
+                        cd 80-cdn
+                        if [ ${params.ACTION} == 'apply' ]
+                        then
                             terraform apply -auto-approve tfplan
-                        elif [ "${params.ACTION}" == "destroy" ]
-                         then
-                            terraform destroy -auto-approve
                         fi
                     """
                 }
             }
         }
-        
+
+        /* stage('Destroy') {
+            when {
+                expression { params.ACTION == 'destroy' }
+            }
+            parallel {
+                stage('ECR') {
+                    steps {
+                        build job: '70-ecr', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
+                    }
+                }
+                stage('ALB') {
+                    steps {
+                        build job: '60-alb', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
+                    }
+                }
+                stage('EKS') {
+                    steps {
+                        build job: '40-eks', parameters: [string(name: 'ACTION', value: "destroy")], wait: true
+                    }
+                }
+                stage('Bastion') {
+                    steps {
+                        build job: '20-bastion', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
+                    }
+                }
+
+            }
+        } */
+        stage('Destroy'){
+            when {
+                expression { params.ACTION == 'destroy' }
+            }
+            steps{
+                withAWS(region: 'us-east-1', credentials: 'as creds') {
+                    script {
+                        def directories = ['80-cdn', '70-ecr', '60-alb', '50-acm', '40-eks', '30-rds', '20-bastion', '10-sg', '00-vpc']
+                        for (dir in directories) {
+                            echo "Destroying resources in directory: ${dir}"
+                            sh """
+                            cd ${dir}
+                            terraform init -reconfigure
+                            terraform destroy -auto-approve || { echo "Failed to destroy resources in ${dir}"; exit 1; }
+                            cd ..
+                            """
+                        }
+            }
+                }
+            }
+        }
+        /* stage('Sequential') {
+            when {
+                expression { params.ACTION == 'destroy' }
+            }
+            stages {
+                
+                stage('ACM') {
+                    steps {
+                        build job: '50-acm', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
+                    }
+                }
+                stage('SG-Destroy'){
+                    steps {
+                        build job: '10-sg', parameters: [string(name: 'ACTION', value: "destroy")], wait: true
+                    }
+                }
+                stage('VPC-Destroy'){
+                    steps {
+                        build job: '00-vpc', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
+                    }
+                }
+            }
+                
+        } */
         
     }
 
     post {
-        always {
-            echo "this section runs always"
+        always{
+            echo "This sections runs always"
             deleteDir()
         }
-
-        success {
-            echo "this section runs when pipeline success"
+        success{
+            echo "This section run when pipeline success"
         }
-
-        failure {
-            echo "this section runs when pipeline fails"
+        failure{
+            echo "This section run when pipeline failure"
         }
     }
 }
